--liquibase formatted sql

--changeset CreateTable_MedicalEmployerJobPosting
CREATE TABLE MedicalEmployerJobPosting (
	MedicalEmployerJobPostingId		INT				AUTO_INCREMENT,
	MedicalEmployerUserId			INT				NOT NULL,
    Title							VARCHAR(512)	NOT NULL,
	Speciality						VARCHAR(512)	NOT NULL,
	JobDescription					TEXT			NULL,
	AssignmentTypeId				INT				NULL,
	AssignmentShiftTypeId			INT				NULL,
	Supervised						BIT				NULL	DEFAULT 0,
	PrescriptionAuthorityNeeded		BIT				NULL	DEFAULT 0,
	AssignmentFromDate				DATE			NULL,
	AssignmentToDate				DATE			NULL,
	CompensationRange				VARCHAR(128)	NULL,
	Compensation					INT				NULL,
	CompensationTypeId				INT				NULL,
	MalpracticeAccepted				BIT				NULL	DEFAULT 0,
	MalpracticeCoverage				BIT				NULL	DEFAULT 0,
	CredentialingCoverage			BIT				NULL	DEFAULT 0,
	LicenseCoverage					BIT				NULL	DEFAULT 0,
	TravelHousingCoverage			BIT				NULL	DEFAULT 0,
	YearsExperience					INT				NULL,
	Priority1						INT				NULL,
	Priority2						INT				NULL,
	Priority3						INT				NULL,
	Priority4						INT				NULL,
	Priority5						INT				NULL,
	PostedDate						DATE			NULL,
	UpdatedDate						DATE			NULL,
	StatusTypeId					INT				NULL,
	ExpiryDate						DATE			NULL,
    State							VARCHAR(128)	NULL,
    Lud								DATETIME		NULL,
    Lub								INT				NULL,
	CONSTRAINT pkMedicalEmployerJobPosting PRIMARY KEY CLUSTERED (MedicalEmployerJobPostingId),
    CONSTRAINT fkMedicalEmployerJobPostingMedicalEmployerUserId FOREIGN KEY (MedicalEmployerUserId) REFERENCES Users (UserId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingAssignmentTypeId FOREIGN KEY (AssignmentTypeId) REFERENCES EnumAssignmentType (AssignmentTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingAssignmentShiftTypeId FOREIGN KEY (AssignmentShiftTypeId) REFERENCES EnumShiftType (ShiftTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingPriority1 FOREIGN KEY (Priority1) REFERENCES EnumPriorityFeatureType (PriorityFeatureTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingPriority2 FOREIGN KEY (Priority2) REFERENCES EnumPriorityFeatureType (PriorityFeatureTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingPriority3 FOREIGN KEY (Priority3) REFERENCES EnumPriorityFeatureType (PriorityFeatureTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingPriority4 FOREIGN KEY (Priority4) REFERENCES EnumPriorityFeatureType (PriorityFeatureTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingPriority5 FOREIGN KEY (Priority5) REFERENCES EnumPriorityFeatureType (PriorityFeatureTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingCompensationTypeId FOREIGN KEY (CompensationTypeId) REFERENCES EnumCompensationType (CompensationTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkMedicalEmployerJobPostingStatusTypeId FOREIGN KEY (StatusTypeId) REFERENCES EnumJobPostingStatusType (JobPostingStatusTypeId) ON UPDATE NO ACTION ON DELETE NO ACTION
);
--rollback DROP TABLE MedicalEmployerJobPosting;